# 时间序列分析

In [1]:
import pandas as pd
import numpy as np

## python 和 pandas 日期工具的区别

In [3]:
import datetime
date = datetime.date(year=2013, month=6, day=7)
time = datetime.time(hour=12, minute=30, second=19, microsecond=463198)
dt = datetime.datetime(year=2013, month=6, day=7, hour=12, minute=30, second=19, microsecond=463198)
print("date is ", date)
print("time is", time)
print("datetime is", dt)

date is  2013-06-07
time is 12:30:19.463198
datetime is 2013-06-07 12:30:19.463198

In [4]:
td = datetime.timedelta(weeks=2, days=5, hours=10, minutes=20, seconds=6.73, milliseconds=99, microseconds=8)
print(td)

19 days, 10:20:06.829008

In [5]:
# date 和 datetime 可以和 timedelta 一起使用
print('new date is', date + td)
print('new datetime is', dt + td)

new date is 2013-06-26
new datetime is 2013-06-26 22:50:26.292206

In [5]:
# time 不能和 timedelta 一起使用
time + td

TypeError: unsupported operand type(s) for +: 'datetime.time' and 'datetime.timedelta'

In [7]:
# Timestamp 可以处理多种输入
pd.Timestamp(year=2012, month=12, day=21, hour=5, minute=10, second=8, microsecond=99)

Timestamp('2012-12-21 05:10:08.000099')

In [8]:
pd.Timestamp('2016/1/10')

Timestamp('2016-01-10 00:00:00')

In [9]:
pd.Timestamp('2014-5/10')

Timestamp('2014-05-10 00:00:00')

In [10]:
pd.Timestamp('Jan 3, 2019 20:45.56')

Timestamp('2019-01-03 20:45:33')

In [11]:
pd.Timestamp('2016-01-05T05:34:43.123456789')

Timestamp('2016-01-05 05:34:43.123456789')

In [12]:
pd.Timestamp(500)  # 默认单位纳秒

Timestamp('1970-01-01 00:00:00.000000500')

In [13]:
''' 
unit 参数支持的时间单位：
    - 'D'：天
    - 'h'：小时
    - 'min'：分钟
    - 's'：秒
    - 'ms'：毫秒
'''

pd.Timestamp(5000, unit='D')

Timestamp('1983-09-10 00:00:00')

In [14]:
# to_datetime 和 Timestamp 类似
'''
主要差异：

1. 输入类型：
    to_datetime 支持多种格式（字符串/数值/数组）
    Timestamp 仅接受明确的时间表示

2. 返回值：
    to_datetime 返回 DatetimeIndex 或 Series
    Timestamp 返回单个时间点对象

3. 参数差异：
    to_datetime 含 format/errors 参数
    Timestamp 含 unit/tz 时区参数

最佳实践：
    1. 处理数据列 → 用 to_datetime
    2. 创建时间常量 → 用 Timestamp
'''
pd.to_datetime('2015-5-13')

Timestamp('2015-05-13 00:00:00')

In [15]:
pd.to_datetime('2015-13-5', dayfirst=True)

Timestamp('2015-05-13 00:00:00')

In [16]:
pd.Timestamp('Saturday September 30th,2017')

Timestamp('2017-09-30 00:00:00')

In [17]:
# to_datetime 可以将多个字符串转换为日期对象
pd.to_datetime('Start Date: Sep 30, 2017 Start Time: 1:30 pm', format='Start Date: %b %d, %Y Start Time: %I:%M %p')

Timestamp('2017-09-30 13:30:00')

In [18]:
pd.to_datetime(100, unit='D', origin='2013-1-1')

Timestamp('2013-04-11 00:00:00')

In [19]:
# to_datetime 可以将一个字符串或者整数列表 或者 series 转换为时间戳
s = pd.Series([10, 100, 1000, 10000])
pd.to_datetime(s, unit='D')

0   1970-01-11
1   1970-04-11
2   1972-09-27
3   1997-05-19
dtype: datetime64[ns]

In [37]:
s = pd.Series(['12-5-2015', '14-1-2013', '20/12/2017', '12/20/2017', '20-12-2017', '40/23/2017', '40-23-2017'])  # dayfirst=True 对斜杠格式无效
pd.to_datetime(s, dayfirst=True, errors='coerce')

0   2015-05-12
1   2013-01-14
2          NaT
3          NaT
4   2017-12-20
5          NaT
6          NaT
dtype: datetime64[ns]

In [41]:
pd.to_datetime(s, format='%d/%m/%Y', errors='coerce')  # 可以用 format 参数指定日期格式

0          NaT
1          NaT
2   2017-12-20
3          NaT
4          NaT
5          NaT
6          NaT
dtype: datetime64[ns]

In [34]:
s = pd.Series(['20/12/2017', '12/20/2017']) 
pd.to_datetime(s, dayfirst=True, errors='coerce')  # dayfirst=True：指定日期格式为 日/月/年

0   2017-12-20
1          NaT
dtype: datetime64[ns]

In [47]:
s = pd.Series(['12/20/2017'])  # 斜杠格式默认按 月/日/年 解析
pd.to_datetime(s, errors='coerce')

0   2017-12-20
dtype: datetime64[ns]

In [49]:
pd.to_datetime(['Aug 3 1999 3:45:56'])

DatetimeIndex(['1999-08-03 03:45:56'], dtype='datetime64[ns]', freq=None)

In [50]:
pd.to_datetime(['10/31/2017'])

DatetimeIndex(['2017-10-31'], dtype='datetime64[ns]', freq=None)

In [53]:
# 如果日期格式混合且不一致，则使用 to_datetime 函数, pd.to_datetime() 默认情况下无法处理格式不一致的日期字符串
pd.to_datetime(['Aug 3 1999 3:45:56', '10/31/2017'], format='mixed')  # 可以使用 format='mixed' 让 pandas 自动推断格式。

DatetimeIndex(['1999-08-03 03:45:56', '2017-10-31 00:00:00'], dtype='datetime64[ns]', freq=None)

In [54]:
# Pandas的Timedelta和to_timedelta也可以用来表示一定的时间量。
# to_timedelta函数可以产生一个Timedelta对象。
# 与to_datetime类似，to_timedelta也可以转换列表或系列变成时间差对象。
pd.Timedelta('12 days 5 hours 3minutes 123456789 nanoseconds')

Timedelta('12 days 05:03:00.123456789')

In [55]:
pd.Timedelta(days=5, minutes=7.34)

Timedelta('5 days 00:07:20.400000')

In [56]:
pd.Timedelta(100, unit='W')

Timedelta('700 days 00:00:00')

In [57]:
pd.to_timedelta('5 dayz', errors='ignore')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26652\948309838.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_timedelta without passing `errors` and catch exceptions explicitly instead
  pd.to_timedelta('5 dayz', errors='ignore')

'5 dayz'

In [58]:
pd.to_timedelta('67:15:45.454')

Timedelta('2 days 19:15:45.454000')

In [59]:
s = pd.Series([10, 100])
pd.to_timedelta(s, unit='s')

0   0 days 00:00:10
1   0 days 00:01:40
dtype: timedelta64[ns]

In [60]:
time_strings = ['2 days 24 minutes89.67 seconds', '00:45:23.6']
pd.to_timedelta(time_strings)

TimedeltaIndex(['2 days 00:25:29.670000', '0 days 00:45:23.600000'], dtype='timedelta64[ns]', freq=None)

In [61]:
pd.Timedelta('12 days 5 hours 3minutes') * 2

Timedelta('24 days 10:06:00')

In [62]:
pd.Timestamp('1/1/2017') + pd.Timedelta('12 days 5 hours 3 minutes') * 2

Timestamp('2017-01-25 10:06:00')

In [63]:
td1 = pd.to_timedelta([10, 100], unit='s')
td2 = pd.to_timedelta(['3 hours', '4hours'])
td1 + td2

TimedeltaIndex(['0 days 03:00:10', '0 days 04:01:40'], dtype='timedelta64[ns]', freq=None)

In [64]:
pd.Timedelta('12 days') / pd.Timedelta('3 days')

4.0

In [68]:
ts = pd.Timestamp('2016-10-1 4:23:23.9')

In [69]:
ts.ceil('h')  # 将时间戳向上舍入到指定的频率(h)

Timestamp('2016-10-01 05:00:00')

In [70]:
ts.year, ts.month, ts.day, ts.hour, ts.minute, ts.second

(2016, 10, 1, 4, 23, 23)

In [71]:
# ts.dayofweek: 这个属性返回一个整数，表示该日期是星期几
# ts.dayofyear: 这个属性返回一个整数，表示该日期是该年份中的第几天
# ts.daysinmonth: 这个属性返回一个整数，表示该日期所在月份的天数
ts.dayofweek, ts.dayofyear, ts.daysinmonth

(5, 275, 31)

In [72]:
ts.to_pydatetime()  # 将 Timestamp 对象转换为 Python 的原生 datetime 对象

datetime.datetime(2016, 10, 1, 4, 23, 23, 900000)

In [73]:
td = pd.Timedelta(125.8723, unit='h')
td

Timedelta('5 days 05:52:20.280000')

In [74]:
td.round('min')  # 将时间间隔四舍五入到最接近的分钟

Timedelta('5 days 05:52:00')

In [75]:
td.components  # 返回一个包含时间间隔各个组成部分的命名元组

Components(days=5, hours=5, minutes=52, seconds=20, milliseconds=280, microseconds=0, nanoseconds=0)

In [76]:
td.total_seconds()

453140.28

In [77]:
date_string_list = ['Sep 30 1984'] * 10000

In [81]:
%%timeit
pd.to_datetime(date_string_list, format='%b %d %Y')

6.83 ms ± 156 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [82]:
%%timeit 
pd.to_datetime(date_string_list)

7.22 ms ± 85.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

## 智能切分时间序列

In [84]:
crime = pd.read_hdf('crime.h5', 'crime')
crime.dtypes

OFFENSE_TYPE_ID              category
OFFENSE_CATEGORY_ID          category
REPORTED_DATE          datetime64[ns]
GEO_LON                       float64
GEO_LAT                       float64
NEIGHBORHOOD_ID              category
IS_CRIME                        int64
IS_TRAFFIC                      int64
dtype: object

In [85]:
crime = crime.set_index('REPORTED_DATE')
crime.head()

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2014-06-29 02:01:00,traffic-accident-dui-duid,traffic-accident,-105.000149,39.745753,cbd,0,1
2014-06-29 01:54:00,vehicular-eluding-no-chase,all-other-crimes,-104.884660,39.738702,east-colfax,1,0
2014-06-29 02:00:00,disturbing-the-peace,public-disorder,-105.020719,39.706674,athmar-park,1,0
2014-06-29 02:18:00,curfew,public-disorder,-105.001552,39.769505,sunnyside,1,0
2014-06-29 04:17:00,aggravated-assault,aggravated-assault,-105.018557,39.679229,college-view-south-platte,1,0

In [86]:
# 可以进行时间部分匹配
pd.options.display.max_rows = 4
crime.loc['2016-05-12 16:45:00']

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2016-05-12 16:45:00,traffic-accident,traffic-accident,-104.847024,39.779596,montbello,0,1
2016-05-12 16:45:00,traffic-accident,traffic-accident,-105.049180,39.769296,west-highland,0,1
2016-05-12 16:45:00,fraud-identity-theft,white-collar-crime,-104.931971,39.717359,hilltop,1,0

In [87]:
crime.loc['2016-05-12']

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2016-05-12 23:51:00,criminal-mischief-other,public-disorder,-105.017241,39.705845,athmar-park,1,0
2016-05-12 18:40:00,liquor-possession,drug-alcohol,-104.995692,39.747875,cbd,1,0
...,...,...,...,...,...,...,...
2016-05-12 15:59:00,menacing-felony-w-weap,aggravated-assault,-104.935172,39.723703,hilltop,1,0
2016-05-12 16:39:00,assault-dv,other-crimes-against-persons,-104.974700,39.740555,north-capitol-hill,1,0

In [88]:
crime.loc['2016-05'].shape

(8012, 7)

In [89]:
crime.loc['2016'].shape

(91076, 7)

In [90]:
crime.loc['2016-05-12 03'].shape

(4, 7)

In [91]:
crime.loc['Dec 2015'].sort_index()

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2015-12-01 00:48:00,drug-cocaine-possess,drug-alcohol,-104.891681,39.740155,east-colfax,1,0
2015-12-01 00:48:00,theft-of-motor-vehicle,auto-theft,-104.891681,39.740155,east-colfax,1,0
...,...,...,...,...,...,...,...
2015-12-31 23:45:00,violation-of-restraining-order,all-other-crimes,-105.034887,39.741827,west-colfax,1,0
2015-12-31 23:50:00,weapon-poss-illegal-dangerous,all-other-crimes,-105.032769,39.709188,westwood,1,0

In [92]:
crime.loc['2016 Sep, 15'].shape

(252, 7)

In [99]:
crime.loc['21st October 2014 05'].shape

(4, 7)

In [102]:
crime_sorted = crime.sort_index()
crime_sorted.loc['2015-3-4':'2016-1-1'].sort_index()

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2015-03-04 00:11:00,assault-dv,other-crimes-against-persons,-105.021966,39.770883,sunnyside,1,0
2015-03-04 00:19:00,assault-dv,other-crimes-against-persons,-104.978988,39.748799,five-points,1,0
...,...,...,...,...,...,...,...
2016-01-01 23:45:00,drug-cocaine-possess,drug-alcohol,-104.987310,39.753598,five-points,1,0
2016-01-01 23:48:00,drug-poss-paraphernalia,drug-alcohol,-104.986020,39.752541,five-points,1,0

In [107]:
crime_sorted.loc['2015-3-4 22':'2016-1-1 23:45:00'].sort_index()

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2015-03-04 22:25:00,traffic-accident-hit-and-run,traffic-accident,-104.973896,39.769064,five-points,0,1
2015-03-04 22:30:00,traffic-accident,traffic-accident,-104.906412,39.632816,hampden-south,0,1
...,...,...,...,...,...,...,...
2016-01-01 23:40:00,robbery-business,robbery,-105.039236,39.726157,villa-park,1,0
2016-01-01 23:45:00,drug-cocaine-possess,drug-alcohol,-104.987310,39.753598,five-points,1,0

In [108]:
mem_cat = crime.memory_usage().sum()
mem_obj = crime.astype({'OFFENSE_TYPE_ID':'object', 
                        'OFFENSE_CATEGORY_ID':'object', 
                        'NEIGHBORHOOD_ID':'object'})\
                .memory_usage(deep=True)\
                .sum()
mb = 2 ** 20
round(mem_cat / mb, 1), round(mem_obj / mb, 1)

(np.float64(35.5), np.float64(118.3))

In [109]:
crime.index[:2]

DatetimeIndex(['2014-06-29 02:01:00', '2014-06-29 01:54:00'], dtype='datetime64[ns]', name='REPORTED_DATE', freq=None)

In [116]:
%timeit crime_sorted.loc['2015-3-4':'2016-1-1']

1.08 ms ± 18.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [119]:
pd.options.display.max_rows = 60

## 只使用适用于 datetimeindex 的方法

In [ ]:
crime = pd.read_hdf('crime.h5', 'crime').set_index('REPORTED_DATE')
print(type(crime.index))

In [ ]:
crime.between_time('2:00', '5:00', include_end=False).head()

In [ ]:
crime.at_time('5:47').head()

In [ ]:
crime_sort = crime.sort_index()

In [ ]:
pd.options.display.max_rows = 6

In [ ]:
crime_sort.first(pd.offsets.MonthBegin(6))

In [ ]:
crime_sort.first(pd.offsets.MonthEnd(6))

In [ ]:
crime_sort.first(pd.offsets.MonthBegin(6, normalize=True))

In [ ]:
crime_sort.loc[:'2012-06']

In [ ]:
crime_sort.first('5D')

In [ ]:
crime_sort.first('5B')

In [ ]:
crime_sort.first('7W')

In [ ]:
crime_sort.first('3QS')

In [ ]:
import datetime
crime.between_time(datetime.time(2,0), datetime.time(5,0), include_end=False)

In [ ]:
first_date = crime_sort.index[0]
first_date

In [ ]:
first_date + pd.offsets.MonthBegin(6)

In [ ]:
first_date + pd.offsets.MonthEnd(6)

In [ ]:
dt = pd.Timestamp('2012-1-16 13:40')
dt + pd.DateOffset(months=1)

In [ ]:
do = pd.DateOffset(years=2, months=5, days=3, hours=8, seconds=10)
pd.Timestamp('2012-1-22 03:22') + do

In [ ]:
pd.options.display.max_rows=60

## 举例1 -- 计算每周的犯罪数

In [ ]:
crime_sort = pd.read_hdf('crime.h5', 'crime') \
                .set_index('REPORTED_DATE') \
                .sort_index()

crime_sort.resample('W')

In [ ]:
weekly_crimes = crime_sort.resample('W').size()
weekly_crimes.head()

In [ ]:
len(crime_sort.loc[:'2012-1-8'])

In [ ]:
len(crime_sort.loc['2012-1-9':'2012-1-15'])

In [ ]:
crime_sort.resample('W-THU').size().head()

In [ ]:
weekly_crimes_gby = crime_sort.groupby(pd.Grouper(freq='W')).size()
weekly_crimes_gby.head()

In [ ]:
weekly_crimes.equals(weekly_crimes_gby)

In [ ]:
r = crime_sort.resample('W')
resample_methods = [attr for attr in dir(r) if attr[0].islower()]
print(resample_methods)

In [ ]:
crime = pd.read_hdf('crime.h5', 'crime')
weekly_crimes2 = crime.resample('W', on='REPORTED_DATE').size()
weekly_crimes2.equals(weekly_crimes)

In [ ]:
weekly_crimes_gby2 = crime.groupby(pd.Grouper(key='REPORTED_DATE', freq='W')).size()
weekly_crimes_gby2.equals(weekly_crimes_gby)

In [ ]:
weekly_crimes.plot(figsize=(16,4), title='All Denver Crimes')

## 举例2 -- 分别聚合每周犯罪和交通事故数据

In [ ]:
crime_sort = pd.read_hdf('crime.h5', 'crime') \
                .set_index('REPORTED_DATE') \
                .sort_index()

In [ ]:
crime_quarterly = crime_sort.resample('Q')['IS_CRIME', 'IS_TRAFFIC'].sum()
crime_quarterly.head()

In [ ]:
crime_sort.resample('QS')['IS_CRIME', 'IS_TRAFFIC'].sum().head()

In [ ]:
crime_sort.loc['2012-4-1':'2012-6-30', ['IS_CRIME', 'IS_TRAFFIC']].sum()

In [ ]:
crime_quarterly2 = crime_sort.groupby(pd.Grouper(freq='Q'))['IS_CRIME', 'IS_TRAFFIC'].sum()
crime_quarterly2.equals(crime_quarterly)

In [ ]:
plot_kwargs = dict(figsize=(16,4), color=['black', 'lightgrey'], title='DenverCrimes and Traffic Accidents')
crime_quarterly.plot(**plot_kwargs)

In [ ]:
crime_sort.resample('Q').sum().head()

In [ ]:
crime_sort.resample('QS-MAR')['IS_CRIME', 'IS_TRAFFIC'].sum().head()

In [ ]:
crime_begin = crime_quarterly.iloc[0]
crime_begin

In [ ]:
crime_quarterly.div(crime_begin) \
                .sub(1) \
                .round(2) \
                .plot(**plot_kwargs)

## 举例3 -- 按工作日和年测量犯罪

In [ ]:
crime = pd.read_hdf('crime.h5', 'crime')
crime.head()

In [ ]:
wd_counts = crime['REPORTED_DATE'].dt.weekday_name.value_counts()

In [ ]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
title = 'Denver Crimes and TrafficAccidents per Weekday'
wd_counts.reindex(days).plot(kind='barh', title=title)

In [ ]:
title = 'Denver Crimes and TrafficAccidents per Year'
crime['REPORTED_DATE'].dt.year.value_counts() \
                      .sort_index() \
                      .plot(kind='barh', title=title)

In [ ]:
weekday = crime['REPORTED_DATE'].dt.weekday_name
year = crime['REPORTED_DATE'].dt.year
crime_wd_y = crime.groupby([year, weekday]).size()
crime_wd_y.head(10)

In [ ]:
crime_table = crime_wd_y.rename_axis(['Year', 'Weekday']).unstack('Weekday')
crime_table

In [ ]:
criteria = crime['REPORTED_DATE'].dt.year == 2017
crime.loc[criteria, 'REPORTED_DATE'].dt.dayofyear.max()

In [ ]:
round(272 / 365, 3)

In [ ]:
crime_pct = crime['REPORTED_DATE'].dt.dayofyear.le(272) \
                                  .groupby(year) \
                                  .mean() \
                                  .round(3)
crime_pct

In [ ]:
crime_pct.loc[2012:2016].median()

In [ ]:
crime_table.loc[2017] = crime_table.loc[2017].div(.748).astype('int')
crime_table = crime_table.reindex(columns=days)
crime_table

In [ ]:
import seaborn as sns
sns.heatmap(crime_table, cmap='Greys')

In [ ]:
denver_pop = pd.read_csv('denver_pop.csv', index_col='Year')
denver_pop.plot()

In [ ]:
den_100k = denver_pop.div(100000).squeeze()
crime_table2 = crime_table.div(den_100k, axis='index').astype('int')
crime_table2

In [ ]:
sns.heatmap(crime_table2, cmap='Greys')

In [ ]:
wd_counts.loc[days]

In [ ]:
ADJ_2017 = .748
def count_crime(df, offense_cat):
    df = df[df['OFFENSE_CATEGORY_ID']== offense_cat]
    weekday = df['REPORTED_DATE'].dt.weekday_name
    year = df['REPORTED_DATE'].dt.year
    ct = df.groupby([year, weekday]).size().unstack()
    ct.loc[2017] = ct.loc[2017].div(ADJ_2017).astype('int')
    pop = pd.read_csv('denver_pop.csv', index_col='Year')
    pop = pop.squeeze().div(100000)
    ct = ct.div(pop,
    axis=0).astype('int')
    ct = ct.reindex(columns=days)
    sns.heatmap(ct, cmap='Greys')
    return ct

count_crime(crime, 'auto-theft')

## 用带有 datetimeindex 的匿名函数做分组

In [ ]:
crime_sort = pd.read_hdf('crime.h5', 'crime') \
               .set_index('REPORTED_DATE') \
               .sort_index()

common_attrs = set(dir(crime_sort.index)) &set(dir(pd.Timestamp))
print([attr for attr in common_attrs if attr[0] != '_'])

In [ ]:
crime_sort.index.weekday_name.value_counts()

In [ ]:
crime_sort.groupby(lambda x: x.weekday_name)['IS_CRIME', 'IS_TRAFFIC'].sum()

In [ ]:
funcs = [lambda x: x.round('2h').hour, lambda x: x.year]
cr_group = crime_sort.groupby(funcs)['IS_CRIME', 'IS_TRAFFIC'].sum()
cr_final = cr_group.unstack()
cr_final.style.highlight_max(color='lightgrey')

In [ ]:
cr_final.xs('IS_TRAFFIC', axis='columns', level=0).head()

In [ ]:
cr_final.xs(2016, axis='columns', level=1).head()

## 用时间戳和另一列分组

In [ ]:
employee = pd.read_csv('employee(1).csv', parse_dates=['JOB_DATE', 'HIRE_DATE'], index_col='HIRE_DATE')
employee.head()

In [ ]:
employee.groupby('GENDER')['BASE_SALARY'].mean().round(-2)

In [ ]:
employee.resample('10AS')['BASE_SALARY'].mean().round(-2)

In [ ]:
sal_avg = employee.groupby('GENDER').resample('10AS')['BASE_SALARY'].mean().round(-2)
sal_avg

In [ ]:
sal_avg.unstack('GENDER')

In [ ]:
employee[employee['GENDER'] == 'Male'].index.min()

In [ ]:
employee[employee['GENDER'] == 'Female'].index.min()

In [ ]:
sal_avg2 = employee.groupby(['GENDER', pd.Grouper(freq='10AS')])['BASE_SALARY'].mean().round(-2)
sal_avg2

In [ ]:
sal_final = sal_avg2.unstack('GENDER')
sal_final

In [ ]:
'resample' in dir(employee.groupby('GENDER'))

In [ ]:
'groupby' in dir(employee.resample('10AS'))

In [ ]:
years = sal_final.index.year
years_right = years + 9
sal_final.index = years.astype(str) + '-' + years_right.astype(str)
sal_final

In [ ]:
cuts = pd.cut(employee.index.year, bins=5, precision=0)
cuts.categories.values

In [ ]:
employee.groupby([cuts, 'GENDER'])['BASE_SALARY'].mean().unstack('GENDER').round(-2)

## 举例4 -- 用 merge_asof 找到上次低20%犯罪率

In [ ]:
crime_sort = pd.read_hdf('crime.h5', 'crime') \
               .set_index('REPORTED_DATE') \
               .sort_index()

In [ ]:
crime_sort.index.max()

In [ ]:
crime_sort = crime_sort[:'2017-8']
crime_sort.index.max()

In [ ]:
all_data = crime_sort.groupby([pd.Grouper(freq='M'), 'OFFENSE_CATEGORY_ID']).size()
all_data.head()

In [ ]:
all_data = all_data.sort_values().reset_index(name='Total')
all_data.head()

In [ ]:
goal = all_data[all_data['REPORTED_DATE'] == '2017-8-31'].reset_index(drop=True)
goal['Total_Goal'] = goal['Total'].mul(.8).astype(int)
goal.head()

In [ ]:
pd.merge_asof(goal, all_data, left_on='Total_Goal', right_on='Total', by='OFFENSE_CATEGORY_ID', suffixes=('_Current', '_Last'))

In [ ]:
pd.Period(year=2012, month=5, day=17, hour=14, minute=20, freq='T')

In [ ]:
crime_sort.index.to_period('M')

In [ ]:
ad_period = crime_sort.groupby([lambda x: x.to_period('M'), 'OFFENSE_CATEGORY_ID']).size()
ad_period = ad_period.sort_values() \
                     .reset_index(name='Total') \
                     .rename(columns={'level_0':'REPORTED_DATE'})
ad_period.head()

In [ ]:
cols = ['OFFENSE_CATEGORY_ID', 'Total']
all_data[cols].equals(ad_period[cols])

In [ ]:
aug_2018 = pd.Period('2017-8', freq='M')
goal_period = ad_period[ad_period['REPORTED_DATE'] == aug_2018].reset_index(drop=True)
goal_period['Total_Goal'] = goal_period['Total'].mul(.8).astype(int)
pd.merge_asof(goal_period, ad_period, left_on='Total_Goal', right_on='Total', by='OFFENSE_CATEGORY_ID', suffixes=('_Current', '_Last')).head()