# 合并pandas对象

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## dataframe 添加新的行

In [2]:
names = pd.read_csv('names.csv')
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2

In [3]:
new_data_list = ['Aria', 1]
names.loc[4] = new_data_list
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
4      Aria    1

In [4]:
names.loc['five'] = ['Zach', 3]
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3

In [5]:
names.loc[len(names)] = {'Name':'Zayd', 'Age':2}
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3
6         Zayd    2

In [6]:
names.loc[len(names)] = pd.Series({'Age':32, 'Name':'Dean'})
names

          Name  Age
0     Cornelia   70
1        Abbas   69
2     Penelope    4
3         Niko    2
4         Aria    1
five      Zach    3
6         Zayd    2
7         Dean   32

In [59]:
# append 已被弃用，只能用concat
names = pd.read_csv('names.csv')
new_row = pd.DataFrame([{'Name': 'Aria', 'Age': 1}])
names  = pd.concat([names, new_row])  # 在末尾添加一行，行是 dataframe 格式
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
0      Aria    1

In [57]:
names = pd.read_csv('names.csv')
pd.concat([names, new_row])

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
0      Aria    1

In [15]:
# 用 concat 添加一行（即两个 dataframe 连接）
names = pd.concat([names, new_row], ignore_index=True)  # ignore_index=True：重新给拼接后的 DataFrame 分配索引（index）
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
4      Aria    1
5      Aria    1

In [60]:
# 重命名索引
names = pd.read_csv('names.csv')
names.index = ['Canada', 'Canada', 'USA', 'USA']
names

            Name  Age
Canada  Cornelia   70
Canada     Abbas   69
USA     Penelope    4
USA         Niko    2

In [61]:
names = pd.concat([names, new_row], ignore_index=True)
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2
4      Aria    1

In [20]:
# 创建一个 series 对象
s = pd.Series({'Name': 'Zach', 'Age': 3}, name=len(names))

In [67]:
s

Name    Zach
Age        3
Name: 5, dtype: object

In [64]:
s.to_frame()

         5
Name  Zach
Age      3

In [65]:
s.to_frame().T

   Name Age
5  Zach   3

In [69]:
names = pd.read_csv('names.csv')
names = pd.concat([names, s.to_frame().T], ignore_index=True)  # 需要将s转换为DataFrame再转置才能正确添加
names

       Name Age
0  Cornelia  70
1     Abbas  69
2  Penelope   4
3      Niko   2
4      Zach   3

In [32]:
names = pd.read_csv('names.csv')
s1 = pd.Series({'Name': 'Zach', 'Age': 3}, name=len(names))
s2 = pd.Series({'Name': 'Zayd', 'Age': 2}, name='USA')
names = pd.concat([names, s1.to_frame().T, s2.to_frame().T])
names

         Name Age
0    Cornelia  70
1       Abbas  69
2    Penelope   4
3        Niko   2
4        Zach   3
USA      Zayd   2

In [37]:
bball_16 = pd.read_csv('baseball16.csv')
bball_16.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,altuvjo01,2016,1,HOU,AL,161,640,108,216,42,...,96.0,30.0,10.0,60,70.0,11.0,7.0,3.0,7.0,15.0
1,bregmal01,2016,1,HOU,AL,49,201,31,53,13,...,34.0,2.0,0.0,15,52.0,0.0,0.0,0.0,1.0,1.0
2,castrja01,2016,1,HOU,AL,113,329,41,69,16,...,32.0,2.0,1.0,45,123.0,0.0,1.0,1.0,0.0,9.0
3,correca01,2016,1,HOU,AL,153,577,76,158,36,...,96.0,13.0,3.0,75,139.0,5.0,5.0,0.0,3.0,12.0
4,gattiev01,2016,1,HOU,AL,128,447,58,112,19,...,72.0,2.0,1.0,43,127.0,6.0,4.0,0.0,5.0,12.0

In [38]:
# 选取一行，并将其转换为字典
data_dict = bball_16.iloc[0].to_dict()
print(data_dict)

{'playerID': 'altuvjo01', 'yearID': 2016, 'stint': 1, 'teamID': 'HOU', 'lgID': 'AL', 'G': 161, 'AB': 640, 'R': 108, 'H': 216, '2B': 42, '3B': 5, 'HR': 24, 'RBI': 96.0, 'SB': 30.0, 'CS': 10.0, 'BB': 60, 'SO': 70.0, 'IBB': 11.0, 'HBP': 7.0, 'SH': 3.0, 'SF': 7.0, 'GIDP': 15.0}

In [39]:
# 对这个字典做格式处理，如果是字符串则为空，否则为缺失值
new_data_dict = {k: '' if isinstance(v, str) else np.nan for k, v in data_dict.items()}  # isinstance(v, str)：检查值 v 是否是字符串类型。
print(new_data_dict)

{'playerID': '', 'yearID': nan, 'stint': nan, 'teamID': '', 'lgID': '', 'G': nan, 'AB': nan, 'R': nan, 'H': nan, '2B': nan, '3B': nan, 'HR': nan, 'RBI': nan, 'SB': nan, 'CS': nan, 'BB': nan, 'SO': nan, 'IBB': nan, 'HBP': nan, 'SH': nan, 'SF': nan, 'GIDP': nan}

In [76]:
# 将一行数据添加到 dataframe 非常消耗资源，不建议用
random_data = []
for i in range(1000):
    d = dict()
    for k, v in data_dict.items():
        if isinstance(v, str):
            d[k] = np.random.choice(list('abcde'))  # 用于向字典 d 中添加或更新一个键 k 的值，值是从 'abcde' 这几个字符中随机选择的一个字符
        else:
            d[k] = np.random.randint(10)  # 表示将字典 d 中的键 k 的值设为 np.random.randint(10) 生成的随机整数
    random_data.append(pd.Series(d, name=i + len(bball_16)))

random_data[20].head()

playerID    c
yearID      7
stint       9
teamID      a
lgID        c
Name: 36, dtype: object

In [78]:
%%timeit
# 用 for 循环一行行添加会比较费时
bball_16_copy = bball_16.copy()
for row in random_data:
    bball_16_copy = pd.concat([bball_16_copy, row], ignore_index=True)

1.97 s ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [83]:
%%timeit
# 将 random_data 转成 dataframe ，用 concat 会比较省时
bball_16_copy = bball_16.copy()
random_data_df = pd.DataFrame(random_data, columns=bball_16.columns)
bball_16_copy = pd.concat([bball_16_copy, random_data_df], ignore_index=True)

48.7 ms ± 861 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

## 连接多个dataframe

In [49]:
stocks_2016 = pd.read_csv('stocks_2016.csv', index_col='Symbol')
stocks_2017 = pd.read_csv('stocks_2017.csv', index_col='Symbol')
stocks_2016

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70

In [50]:
stocks_2017

        Shares  Low  High
Symbol
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [51]:
s_list = [stocks_2016, stocks_2017]
pd.concat(s_list)

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [52]:
# keys 参数可以给两个 dataframe 命名，该标签会出现在行索引的最外层，会生成多层索引，names 参数可以重命名每个索引层
pd.concat(s_list, keys=['2016', '2017'], names=['Year', 'Symbol'])

             Shares  Low  High
Year Symbol
2016 AAPL        80   95   110
     TSLA        50   80   130
     WMT         40   55    70
2017 AAPL        50  120   140
     GE         100   30    40
     IBM         87   75    95
     SLB         20   55    85
     TXN        500   15    23
     TSLA       100  100   300

In [53]:
# 也可以横向连接。只要将 axis 参数设为 columns 或 1
pd.concat(s_list, keys=['2016', '2017'], axis='columns', names=['Year', None])

Year     2016                2017
       Shares   Low   High Shares    Low   High
Symbol
AAPL     80.0  95.0  110.0   50.0  120.0  140.0
TSLA     50.0  80.0  130.0  100.0  100.0  300.0
WMT      40.0  55.0   70.0    NaN    NaN    NaN
GE        NaN   NaN    NaN  100.0   30.0   40.0
IBM       NaN   NaN    NaN   87.0   75.0   95.0
SLB       NaN   NaN    NaN   20.0   55.0   85.0
TXN       NaN   NaN    NaN  500.0   15.0   23.0

In [54]:
# concat 函数默认使用的是外连接，会保留每个 dataframe 中
pd.concat(s_list, join='inner', keys=['2016', '2017'], axis='columns', names=['Year', None])  # join='inner'：只保留在所有 DataFrame中都有的列

Year     2016            2017
       Shares Low High Shares  Low High
Symbol
AAPL       80  95  110     50  120  140
TSLA       50  80  130    100  100  300

## concat,join和merge的区别

concat：
- Pandas函数
- 可以垂直和水平地连接两个或多个pandas对象
- 只用索引对齐
- 索引出现重复值时会报错
- 默认是外连接（也可以设为内连接）

join：
- DataFrame方法
- 只能水平连接两个或多个pandas对象
- 对齐是靠被调用的DataFrame的列索引或行索引和另一个
- 对象的行索引（不能是列索引
- 通过笛卡尔积处理重复的索引值
- 默认是左连接（也可以设为内连接、外连接和右连接）

merge：
- DataFrame方法
- 只能水平连接两个DataFrame对象
- 对齐是靠被调用的DataFrame的列或行索引和另一个
- DataFrame的列或行索引
- 通过笛卡尔积处理重复的索引值
- 默认是内连接（也可以设为左连接、外连接、右连接）

In [ ]:
from IPython.display import display_html
years = 2016, 2017, 2018
stock_tables = [pd.read_csv('stocks_{}.csv'.format(year), index_col='Symbol') for year in years]

def display_frames(frames, num_spaces=0):
    t_style = '<table style="display:inline;"'
    tables_html = [df.to_html().replace('<table', t_style) for df in frames]
    space = '&nbsp;' * num_spaces
    display_html(space.join(tables_html), raw=True)

display_frames(stock_tables, 30)
stocks_2016, stocks_2017, stocks_2018 = stock_tables

In [ ]:
pd.concat(stock_tables, keys=[2016, 2017, 2018])

In [ ]:
pd.concat(dict(zip(years,stock_tables)), axis='columns')

In [ ]:
stocks_2016.join(stocks_2017, lsuffix='_2016', rsuffix='_2017', how='outer')

In [ ]:
stocks_2016

In [ ]:
other = [stocks_2017.add_suffix('_2017'), stocks_2018.add_suffix('_2018')]
 
stocks_2016.add_suffix('_2016').join(other, how='outer')

In [ ]:
stock_join = stocks_2016.add_suffix('_2016').join(other, how='outer')
stock_concat = pd.concat(dict(zip(years,stock_tables)), axis='columns')

stock_concat.columns = stock_concat.columns.get_level_values(1) + '_' + \
                       stock_concat.columns.get_level_values(0).astype(str)

stock_concat

In [ ]:
step1 = stocks_2016.merge(stocks_2017, left_index=True, right_index=True, how='outer', suffixes=('_2016', '_2017'))
stock_merge = step1.merge(stocks_2018.add_suffix('_2018'), left_index=True, right_index=True, how='outer')
stock_concat.equals(stock_merge)

In [ ]:
names = ['prices', 'transactions']
food_tables = [pd.read_csv('data/food_{}.csv'.format(name)) for name in names]
food_prices, food_transactions = food_tables
display_frames(food_tables, 30)

In [ ]:
food_transactions.merge(food_prices, on=['item', 'store'])

In [ ]:
food_transactions.merge(food_prices.query('Date== 2017'), how='left')

In [ ]:
food_prices_join = food_prices.query('Date ==2017').set_index(['item', 'store'])
food_prices_join

In [ ]:
food_transactions.join(food_prices_join, on=['item', 'store'])

In [ ]:
pd.concat([food_transactions.set_index(['item', 'store']), food_prices.set_index(['item', 'store'])], axis='columns')

In [ ]:
import glob
df_list = []
for filename in glob.glob('data/gasprices/*.csv'):
    df_list.append(pd.read_csv(filename, index_col='Week', parse_dates=['Week']))

gas = pd.concat(df_list, axis='columns')
gas.head()

## 连接 sql 数据库